config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'
  #get 'pages/landing'
  get 'pages/about'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

<div class="container-fluid container-background"> 
  <div class="container"> 


    <ul class="nav">
      <li class="nav-item nav-link">
        <%= link_to "Main", root_path, class:'nav-landing' %> 
      </li>
      <li class="nav-item nav-link">
        <%= link_to "About Me", pages_about_path, class:'nav-landing' %>
      </li>
    </ul>    
    
<%= yield %>
  </div>  <%# ./container%>
</div> <%# ./ontainer-fluid%>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="h1-font-size">Інформація про блог</h1>
  <p class="lead">Детальний опис фото</p>
</div> 

app/views/pages/landing.html.erb
<div class="jumbotron jumbotron-landing">
  <h1 class="h1-font-size">Діліться своїми емоціями</h1>
  <p class="lead">Розміщуйте свої фотографії та пишіть коментарі</p>
  <hr class="m-y-2">

  <p class="lead">
    <a class="btn btn-warning" href="#" role="button">Створити акаунт</a>
    <a class="btn  btn-primary" href="#" role="button">Вхід</a>
  </p>
</div> 